import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import List from "./components/List";
import Creator from "./components/Creator";
import Displayer from "./components/Displayer";

export default function Home() {
  const [title, setTitle] = useState();
  const [body, setBody] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Note App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <List></List>
      <Creator></Creator>
      <Displayer></Displayer>
    </div>
  );
}
